/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library-Management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shweta Sindhu
 */
public class Admin extends javax.swing.JFrame {
Connection con=DbConnect.getConnection();
    /**
     
     */
    public Admin() {
        initComponents();
        Library.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
    @Override
    protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
        return 0; // This effectively hides the tab area
    }
});
        updatePenalties();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Library = new javax.swing.JTabbedPane();
        iBook = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        stdid = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        rBook = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        uBook = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        bkname = new javax.swing.JTextField();
        aname = new javax.swing.JTextField();
        available = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        addStd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        bname = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycollege/BV.png"))); // NOI18N
        jLabel1.setText("E-Library");

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton7.setText("LogOut");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton9.setText("BOOKS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 102, 102));
        jButton10.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton10.setText("RETURN");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(102, 102, 102));
        jButton11.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton11.setText("ISSUE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        iBook.setBackground(new java.awt.Color(0, 91, 104));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Book Name");

        bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Student ID");

        jButton13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton13.setText("Clear");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("Book ID");

        jButton16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton16.setText("Search");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton17.setText("Issue");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iBookLayout = new javax.swing.GroupLayout(iBook);
        iBook.setLayout(iBookLayout);
        iBookLayout.setHorizontalGroup(
            iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iBookLayout.createSequentialGroup()
                .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iBookLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(iBookLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel15)))
                .addGap(124, 124, 124)
                .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookid)
                    .addComponent(bookname)
                    .addComponent(stdid))
                .addGap(233, 233, 233))
            .addGroup(iBookLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );
        iBookLayout.setVerticalGroup(
            iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iBookLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(57, 57, 57)
                .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(iBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        Library.addTab("BOOK ISSUE", iBook);

        rBook.setBackground(new java.awt.Color(153, 153, 0));
        rBook.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("  Student id");

        jButton14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton14.setText("issued  Books");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton15.setText("Returned Book");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout rBookLayout = new javax.swing.GroupLayout(rBook);
        rBook.setLayout(rBookLayout);
        rBookLayout.setHorizontalGroup(
            rBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rBookLayout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(rBookLayout.createSequentialGroup()
                .addGroup(rBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rBookLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(stid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rBookLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton14))
                    .addGroup(rBookLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rBookLayout.setVerticalGroup(
            rBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rBookLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(rBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(stid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton15)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        Library.addTab("RETURN BOOK", rBook);

        uBook.setBackground(new java.awt.Color(135, 111, 151));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Book Id");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Book Name");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Author");
        jLabel8.setFocusTraversalPolicyProvider(true);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Available");

        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setText("Add Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton5.setText("Edit Book");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uBookLayout = new javax.swing.GroupLayout(uBook);
        uBook.setLayout(uBookLayout);
        uBookLayout.setHorizontalGroup(
            uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uBookLayout.createSequentialGroup()
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uBookLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(uBookLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))))
                    .addGroup(uBookLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel7))
                    .addGroup(uBookLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton4)))
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uBookLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton5)
                        .addGap(106, 106, 106)
                        .addComponent(jButton8))
                    .addGroup(uBookLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(available, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(bid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bkname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aname, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        uBookLayout.setVerticalGroup(
            uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uBookLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bkname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(49, 49, 49)
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(98, 98, 98)
                .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uBookLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(12, 12, 12))
                    .addGroup(uBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        Library.addTab("BOOKS INFO", uBook);

        addStd.setBackground(new java.awt.Color(127, 171, 185));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("StudentID");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Student Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Course Name");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Branch Name");

        bname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "IT", "AI", "none", " " }));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Add ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addStdLayout = new javax.swing.GroupLayout(addStd);
        addStd.setLayout(addStdLayout);
        addStdLayout.setHorizontalGroup(
            addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStdLayout.createSequentialGroup()
                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStdLayout.createSequentialGroup()
                        .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addStdLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addStdLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addStdLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addGap(353, 353, 353)
                        .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sid)
                                .addComponent(sname)
                                .addComponent(cname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addStdLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1)
                        .addGap(143, 143, 143)
                        .addComponent(jButton2)
                        .addGap(173, 173, 173)
                        .addComponent(jButton3)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        addStdLayout.setVerticalGroup(
            addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStdLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sname)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(90, 90, 90)
                .addGroup(addStdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        Library.addTab("STUDENT INFO", addStd);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton6.setText("STUDENTS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(Library, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Library))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Library.setSelectedIndex(2);
        
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Library.setSelectedIndex(1);
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Library.setSelectedIndex(0);
    }                                         

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Library.setSelectedIndex(3);
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        // TODO add your handling code here:
         try (PreparedStatement preparedStatement = con.prepareStatement(
            "INSERT INTO student (sid, name,course,branch) VALUES (?, ?, ?, ?)")) {
        preparedStatement.setInt(1,Integer.parseInt(sid.getText()));
        preparedStatement.setString(2,sname.getText());
        preparedStatement.setString(4,bname.getSelectedItem().toString());
        preparedStatement.setString(3, cname.getText());
       
        int rowsInserted = preparedStatement.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Student added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
//             new Login().setVisible(true);
//             this.dispose();
//            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Error in inserting data of student, try again", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        
        JOptionPane.showMessageDialog(this, "Database error occurred. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     try (PreparedStatement preparedStatement = con.prepareStatement(
            "INSERT INTO book (bookid, bookname,authorname,available) VALUES (?, ?, ?, ?)")) {
        preparedStatement.setInt(1,Integer.parseInt(bid.getText()));
        preparedStatement.setString(2,bkname.getText());
        preparedStatement.setString(3,aname.getText());
        preparedStatement.setInt(4,Integer.parseInt(available.getText()));
       
        int rowsInserted = preparedStatement.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "books added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error in inserting data of books, try again", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        
        JOptionPane.showMessageDialog(this, "Database error occurred. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        // TODO add your handling code here:
    }                                        

    private void booknameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());
    java.sql.Date returnDate = new java.sql.Date(currentDate.getTime() + 14L * 24 * 60 * 60 * 1000);
    String countSql = "SELECT COUNT(*) FROM issuedbook WHERE studentid = ? AND issueddate = ?";
    String insertSql = "INSERT INTO issuedbook (studentid, bookid, issueddate, returneddate, penalty)" +
                       "VALUES (?, ?, ?, ?, 0)";
    String updateBookSql = "UPDATE book SET available = available - 1 WHERE bookid = ? AND available > 0";
    
    try {
        
        con.setAutoCommit(false);
        try (PreparedStatement countStmt = con.prepareStatement(countSql)) {
            countStmt.setString(1, stdid.getText());  
            countStmt.setDate(2, currentDate);      
            ResultSet resultSet = countStmt.executeQuery();
            resultSet.next();
            int booksIssuedToday = resultSet.getInt(1);
            if (booksIssuedToday >= 3) {
                JOptionPane.showMessageDialog(null, "You cannot issue more than 3 books today.", "Limit Reached", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        try (PreparedStatement insertStmt = con.prepareStatement(insertSql)) {
            insertStmt.setString(1, stdid.getText());   
            insertStmt.setString(2, bookid.getText());  
            insertStmt.setDate(3, currentDate);         
            insertStmt.setDate(4, returnDate);     
            int rowsInserted = insertStmt.executeUpdate();
            if (rowsInserted > 0) {
                try (PreparedStatement updateStmt = con.prepareStatement(updateBookSql)) {
                    updateStmt.setString(1, bookid.getText());  
                    int rowsUpdated = updateStmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Book issued successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No copies available for this book.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Failed to issue book. Try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        con.commit();
    } catch (SQLException e) {
        try {
            con.rollback();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database error occurred during book issuance!", "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            con.setAutoCommit(true);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(bookid.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"enter bookid");
        }
        else{
            try{
           
            PreparedStatement ps=con.prepareStatement("select * from book where bookid=?");
        
        ps.setString(1,bookid.getText());
        
      
        
         ResultSet rs=ps.executeQuery();
        
        if(rs.next())
        {
             
            
             bookname.setText(rs.getString("bookname"));}
        else
        {
              JOptionPane.showMessageDialog(null,"Invalid bookid");
        }
        }catch(Exception e){
            e.printStackTrace();
        }
        }
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
         bookname.setText("");
         bookid.setText("");
         stdid.setText("");
     
    }                                         

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      sid.setText("");
       sname.setText("");
        cname.setText("");

    }                                        

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
                int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a book to return.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

     
        String bookID = table.getValueAt(selectedRow, 0).toString(); 
        String studentID = stid.getText(); 

        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Student ID is required.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            
            con.setAutoCommit(false);
            String updateBookSql = "UPDATE book SET available = available + 1 WHERE bookid = ?";
            PreparedStatement updateBookStmt = con.prepareStatement(updateBookSql);
            updateBookStmt.setString(1, bookID);
            int rowsUpdated = updateBookStmt.executeUpdate();

            if (rowsUpdated == 0) {
                JOptionPane.showMessageDialog(null, "Error updating book availability. Book ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
                con.rollback();
                return;
            }

            String deleteIssuedBookSql = "DELETE FROM issuedbook WHERE studentid = ? AND bookid = ?";
            PreparedStatement deleteIssuedBookStmt = con.prepareStatement(deleteIssuedBookSql);
            deleteIssuedBookStmt.setString(1, studentID);
            deleteIssuedBookStmt.setString(2, bookID);
            int rowsDeleted = deleteIssuedBookStmt.executeUpdate();

            if (rowsDeleted == 0) {
                JOptionPane.showMessageDialog(null, "Error deleting issued book record. No matching record found.", "Error", JOptionPane.ERROR_MESSAGE);
                con.rollback();
                return;
            }

            con.commit();
            JOptionPane.showMessageDialog(null, "Book returned successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            displayStudentIssuedBooks(); 

        } catch (SQLException ex) {
            ex.printStackTrace();
            try {
                con.rollback(); // Rollback the transaction in case of an error
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "An error occurred while returning the book.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                con.setAutoCommit(true); // Restore the default auto-commit behavior
            } catch (SQLException finalEx) {
                finalEx.printStackTrace();
            }
        }
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
displayStudentIssuedBooks();
    }                                         

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        bid.setText("");
        bkname.setText("");
        aname.setText("");
        available.setText("");
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {

    String selectQuery = "SELECT penalty, bookid1,bookid2,bookid3 FROM student WHERE sid = ?";
    PreparedStatement selectStatement = con.prepareStatement(selectQuery);
    selectStatement.setString(1, sid.getText()); // Student ID
    ResultSet resultSet = selectStatement.executeQuery();

    if (resultSet.next()) {
       
        int penalty = resultSet.getInt("penalty");
        
        String updateQuery = "UPDATE student " +
                             "SET name = ?, course = ?, branch = ?, penalty = ?, bookid1 = ?,bookid2 = ?,bookid3 = ? " +
                             "WHERE sid = ?";
        PreparedStatement updateStatement = con.prepareStatement(updateQuery);
        updateStatement.setString(1, sname.getText());
        updateStatement.setString(2, cname.getText()); 
        updateStatement.setString(3, bname.getSelectedItem().toString()); 
        updateStatement.setInt(4, penalty); 
        updateStatement.setString(5,resultSet.getString("bookid1"));
        updateStatement.setString(6,resultSet.getString("bookid2"));
updateStatement.setString(7,resultSet.getString("bookid3"));
        updateStatement.setString(8, sid.getText());

        int rowsUpdated = updateStatement.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Student details updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Student ID does not exist.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Student ID not found.", "Error", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException e) {
  
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error occurred while updating information.", "Error", JOptionPane.ERROR_MESSAGE);
}

        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
String sql = "UPDATE book " +
             "SET bookname = ?, authorname = ?, available = ? " +
             "WHERE bookid = ?";

try {
    PreparedStatement preparedStatement = con.prepareStatement(sql);

    preparedStatement.setString(1, bkname.getText());
    preparedStatement.setString(2, aname.getText()); 
    preparedStatement.setInt(3,  Integer.parseInt(available.getText())); 
    preparedStatement.setString(4,bid.getText()); 
    int rowsUpdated = preparedStatement.executeUpdate();
    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(null, "Book details updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "Book ID does not exist.", "Error", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException e) {

    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error occurred while updating information.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
       int response = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to sign out?",
                "Confirm Sign Out",
                JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
              this.dispose();
            }
        else
             Library.setSelectedIndex(0);
    
    }                                        
public void updatePenalties() {
    String sql = "UPDATE issuedbook " +
                 "SET penalty = {fn TIMESTAMPDIFF(SQL_TSI_DAY, returneddate, CURRENT_DATE)} " +
                 "WHERE returneddate < CURRENT_DATE";

    try (PreparedStatement preparedStatement = con.prepareStatement(sql)) {
        int rowsUpdated = preparedStatement.executeUpdate();
        if (rowsUpdated > 0) {
            System.out.println("Penalties updated successfully for overdue books.");
        } else {
            System.out.println("No overdue books found.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database error occurred while updating penalties.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTabbedPane Library;
    private javax.swing.JPanel addStd;
    private javax.swing.JTextField aname;
    private javax.swing.JTextField available;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bkname;
    private javax.swing.JComboBox<String> bname;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookname;
    private javax.swing.JTextField cname;
    private javax.swing.JPanel iBook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel rBook;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField stdid;
    private javax.swing.JTextField stid;
    private javax.swing.JTable table;
    private javax.swing.JPanel uBook;
    // End of variables declaration                   

    private void displayStudentIssuedBooks() {
        String sql = "SELECT issuedbook.bookid, book.bookname, book.authorname, " +
             "issuedbook.issueddate, issuedbook.returneddate " +
             "FROM issuedbook " +  
             "JOIN book ON issuedbook.bookid = book.bookid " +  
             "WHERE issuedbook.studentid = ?";

try {
   
    PreparedStatement preparedStatement = con.prepareStatement(sql);
    preparedStatement.setString(1, stid.getText()); 
    ResultSet rs = preparedStatement.executeQuery();

    ResultSetMetaData metaData = rs.getMetaData();
    int columnCount = metaData.getColumnCount();
    Vector<String> columnNames = new Vector<>();
   
    for (int i = 1; i <= columnCount; i++) {
        columnNames.add(metaData.getColumnName(i));
    }

    Vector<Vector<Object>> data = new Vector<>();
    while (rs.next()) {
        Vector<Object> row = new Vector<>();
        for (int i = 1; i <= columnCount; i++) {
            row.add(rs.getObject(i));
        }
        data.add(row);
    }

   table.setModel(new DefaultTableModel(data, columnNames));

    rs.close();
    preparedStatement.close();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error loading today's orders: " + e.getMessage());
}
    }
}
